bind_addr = ":8080"

host_db = "localhost"
port_db = ":6543"
name_db = "sber-invest-db"
user_db = "postgres"
password_db = "PostgresInvest2022"

cache_host = "localhost"
cache_password = "RedisInvest2022"
cache_addr = ":6379"

api_secret  ="yoursecretstring"
token_hour__lifespan = "1"